use std::io::Write;

use indoc::formatdoc;

use crate::models::route::{
    ApiParam, ApiParamIn, ApiRequstBody, ApiResponseBody, ApiRoute,
};

use super::*;

pub struct KotlinRoute {
    pub doc: String,
    pub method: String,
    pub url: String,
    pub name: String,
    pub params: Vec<KotlinApiParam>,
    pub request_body: Option<KotlinApiRequstBody>,
    pub response_body: Option<KotlinApiResponseBody>,
}

impl From<ApiRoute> for KotlinRoute {
    fn from(value: ApiRoute) -> Self {
        Self {
            doc: value.doc,
            method: value.method,
            url: value.url,
            name: value.name,
            params: value.params.iter().map(Into::into).collect(),
            request_body: value.request_body.map(Into::into),
            response_body: value.response_body.map(Into::into),
        }
    }
}

#[derive(Debug, Clone)]
pub struct KotlinApiParam {
    pub name: String,
    pub param_in: ApiParamIn,
    pub required: bool,
    pub api_type: KotlinPrim,
}

impl From<&ApiParam> for KotlinApiParam {
    fn from(value: &ApiParam) -> Self {
        Self {
            name: value.name.clone(),
            param_in: value.param_in,
            required: value.required,
            api_type: KotlinPrim::from_aty(&value.api_type),
        }
    }
}

#[derive(Debug, Clone)]
pub struct KotlinApiRequstBody {
    pub content_type: String,
    pub api_type: KotlinPrim,
}

impl From<ApiRequstBody> for KotlinApiRequstBody {
    fn from(value: ApiRequstBody) -> Self {
        Self {
            content_type: value.content_type,
            api_type: KotlinPrim::from_aty(&value.api_type),
        }
    }
}

#[derive(Debug, Clone)]
pub struct KotlinApiResponseBody {
    pub content_type: String,
    pub api_type: Option<KotlinPrim>,
}

impl From<ApiResponseBody> for KotlinApiResponseBody {
    fn from(value: ApiResponseBody) -> Self {
        Self {
            content_type: value.content_type,
            api_type: value.api_type.as_ref().map(|v| KotlinPrim::from_aty(v)),
        }
    }
}

impl KotlinApi {
    pub fn gen_routes(&self) -> std::io::Result<()> {
        let mut s = String::with_capacity(2 * 1024 * 1024);
        let mut kotlin = std::fs::OpenOptions::new()
            .write(true)
            .create(true)
            .truncate(true)
            .open("argon-data/route.kt")?;

        // let json_reader = std::fs::read_to_string("kotlin/json_reader.kt")?;
        // let into_json = std::fs::read_to_string("kotlin/into_json.kt")?;
        // let header = std::fs::read_to_string("kotlin/header.kt")?;

        kotlin.write_all(
            formatdoc! {r#"
                // DO NOT EDIT THIS FILE.
                // THIS IS A GENERATED FILE AND ANY EDIT WILL BE REPLACED
                // Home: github.com/00-team/argon

                package gooje.abi

                import app.gooje.test.api.HttpxProps
                import app.gooje.test.api.ApiClient
                import app.gooje.test.api.ApiResult
                import app.gooje.test.api.result_err
                import okhttp3.MultipartBody
                import okhttp3.MediaType.Companion.toMediaType
                import okhttp3.RequestBody.Companion.toRequestBody

                import app.gooje.test.Logger
                // import okhttp3.MultipartBody


            "#}
            .as_bytes(),
        )?;

        for kr in self.routes.iter() {
            push!(s, "/**\n", &kr.doc, "\n*/\n");
            push!(s, "suspend fun ", &kr.name, "(\n");

            for p in kr.params.iter() {
                push!(s, T1, &p.name, ": ", &p.api_type.generate());
                if p.api_type.is_option() || !p.required {
                    push!(s, " = null");
                }
                push!(s, ",\n");
            }

            if let Some(rqb) = &kr.request_body {
                push!(s, T1, "body: ", &rqb.api_type.generate(), ",\n");
            }

            push! {s, T1, "override: HttpxProps.() -> HttpxProps = { this }\n): ApiResult<"};

            if let Some(rsb) = &kr.response_body {
                match rsb.content_type.as_str() {
                    "text/plain" => {
                        push!(s, "String");
                    }
                    "application/json" => {
                        push!(s, &rsb.api_type.as_ref().unwrap().generate());
                    }
                    _ => unreachable!(),
                }
            } else {
                push!(s, "Unit");
            }

            push!(s, "> {\n");

            let kt_url = kr.url.replace('{', "${");
            if let Some(rqb) = &kr.request_body {
                if rqb.content_type == "text/plain" {
                    push! {s, T1, "val data = body.toRequestBody(\"text/plain\".toMediaType())\n"};
                } else if rqb.content_type == "application/json" {
                } else {
                    assert_eq!(rqb.content_type, "multipart/form-data");

                    push! { s, T1, "val mfb = MultipartBody.Builder().setType(MultipartBody.FORM)\n" };
                    let KotlinPrim::Ref(ty_name) = &rqb.api_type else {
                        unreachable!()
                    };
                    let kob = self.objects.get(ty_name).unwrap();
                    assert!(kob.is_multipart);

                    for f in &kob.fields {
                        push!(s, T1);
                        f.ty.gen_mfb(&format!("body.{}", f.name), &mut s);
                    }

                    push! {s, T1, "val data = mfb.build()\n\n"};
                }
            }

            push! {s,
                T1, "val base_props = HttpxProps(\n",
                T2, "url = \"", &kt_url, "\",\n",
                T2, "method = \"", &kr.method.to_uppercase(), "\",\n",
                T2, "params = mapOf(\n"
            };

            for p in kr.params.iter() {
                if !p.param_in.is_query() {
                    continue;
                }

                push!(s, T3, "\"", &p.name, "\" to ", &p.name, ".toString(),\n");
            }

            push!(s, T2, "),\n");

            if let Some(rqb) = &kr.request_body {
                if rqb.content_type == "application/json" {
                    push!(s, T2, "json = body as gooje.abi.IntoJson,\n");
                } else {
                    push!(s, T2, "data = data,\n");
                }
            }

            push! {s,
                T1, ")\n",
                T1, "val rs = ApiClient.httpx(override(base_props))\n\n",
                T1, "return rs.use { rs -> \n",
                T2, "if (rs.code == 200) {\n",
                T3, "ApiResult.Ok(status = rs.code, body = "
            };

            if let Some(rsb) = &kr.response_body {
                if rsb.content_type == "text/plain" {
                    push!(s, "rs.body.string()");
                } else {
                    assert_eq!(rsb.content_type, "application/json");
                    let ty = &rsb.api_type.as_ref().unwrap();
                    push! {s,
                        "run {\n", 
                        "val json_reader = gooje.abi.JsonReader(rs.body.string())\n",
                        &ty.from_json(),
                        "\n}"
                        // ".from_json(JsonReader(rs.body.string()))!!"
                    };
                    // match ty {
                    //     KotlinPrim::Array(a) => {
                    //         push!(s, "run {\n");
                    //         push!(s, "}");
                    //     },
                    //     KotlinPrim::Map(_) => unreachable!(),
                    //     KotlinPrim::File => unreachable!()
                    //     _ => {
                    //
                    //     }
                    // }
                }
            } else {
                push!(s, "Unit");
            }

            push! {s,
                ")\n",
                T2, "} else {\n",
                T3, "result_err(rs.body.string(), rs.code)\n",
                T2, "}\n",
                T1, "}\n"
            }

            push!(s, "}\n");
        }

        kotlin.write_all(s.as_bytes())?;

        Ok(())
    }
}
