use std::io::Write;

use indoc::formatdoc;

use super::*;

impl KotlinApi {
    pub fn generate(&self) -> std::io::Result<()> {
        let mut s = String::with_capacity(2 * 1024 * 1024);
        let mut tb = String::with_capacity(2 * 1024 * 1024);
        let mut kotlin = std::fs::OpenOptions::new()
            .write(true)
            .create(true)
            .truncate(true)
            .open("argon-data/gen.kt")?;

        let json_reader = std::fs::read_to_string("argon-data/kotlin/json_reader.kt")?;
        let into_json = std::fs::read_to_string("argon-data/kotlin/into_json.kt")?;
        let header = std::fs::read_to_string("argon-data/kotlin/header.kt")?;

        kotlin.write_all(
            formatdoc! {r#"
                // DO NOT EDIT THIS FILE.
                // THIS IS A GENERATED FILE AND ANY EDIT WILL BE REPLACED
                // Home: github.com/00-team/argon

                package gooje.abi

                import app.gooje.qq.Logger
                import okhttp3.MultipartBody
                // import okhttp3.MultipartBody

                const val API_VERSION = "{}";

                {header}
                {into_json}
                {json_reader}


            "#, self.api_version}
            .as_bytes(),
        )?;

        tb.push_str("fun test() {\n\n");

        for (name, kp) in &self.typealias {
            s += &formatdoc! {r#"
                @JvmInline
                value class {name}(private val value: {}): IntoJson {{
                    override fun into_json() = into_json(value);

                    companion object: FromJson<{name}> {{
                        val DEFAULT = {name}({})

                        override fun from_json(json_reader: JsonReader): {name} {{
                            return {name}({})
                        }}
                    }}
                }}
            "#, kp.generate(), kp.default_value(), kp.from_json(),
            };

            tb += &formatdoc! {r#"
                run {{
                    Logger.verbose("milf", "{name}")
                    val json = {name}.DEFAULT.into_json()
                    val parsed = {name}.from_json(JsonReader(json))
                    assert_eq({name}.DEFAULT, parsed)
                }}

            "#};
        }

        for se in &self.str_enums {
            push!(s, "enum class ", &se.name, " : IntoJson {\n", T1);
            for v in &se.variants {
                push!(s, &v.to_uppercase(), ",");
            }
            s.pop();
            push!(s, ";\n\n", T1);
            s.push_str("override fun into_json(): String = when(this) {\n");

            for v in &se.variants {
                push!(s, T2, &v.to_uppercase(), " -> ", r#""\""#, v, r#"\"""#);
                s.push('\n');
            }

            push!(s, T1, "}\n\n", T1);

            s += &format!("companion object: FromJson<{}> {{\n", se.name);
            push!(s, T2, "val DEFAULT = ", &se.name, ".");
            s.push_str(&se.variants[0].to_uppercase());

            push!(s, "\n\n", T2);
            s.push_str("override fun from_json(json_reader: JsonReader): ");
            push! {s,
                &se.name, " {\n",
                T3, "val value = json_reader.next_string()\n",
                T3, "return when (value) {\n"
            };
            for v in &se.variants {
                push! {s, T4, "\"", v, "\" -> ", &se.name, ".", &v.to_uppercase(), "\n"};
            }
            push! {s, T4, r#"else -> throw JsonParseException("unknown enum $value")"#};
            push!(s, "\n", T3, "}\n", T2, "}\n", T1, "}\n}\n");

            tb += &formatdoc! {r#"
                run {{
                    Logger.verbose("milf", "{name}")
                    val json = {name}.DEFAULT.into_json()
                    val parsed = {name}.from_json(JsonReader(json))
                    assert_eq({name}.DEFAULT, parsed)
                }}

            "#, name = se.name,};
        }

        for (_, kob) in &self.objects {
            kob.generate(&mut s, &mut tb);
        }

        for te in &self.tagged_enums {
            te.generate(&mut s, &mut tb);
        }

        s.push_str("\n\n");
        tb.push_str("}\n");

        kotlin.write_all(s.as_bytes())?;
        kotlin.write_all(tb.as_bytes())?;

        Ok(())
    }
}

impl TaggedEnum {
    pub fn generate(&self, s: &mut String, tb: &mut String) {
        tb.push_str(&formatdoc! {r#"
            run {{
                Logger.verbose("milf", "{name}")
                val json = {name}.DEFAULT.into_json()
                Logger.debug("milf", "json: $json")
                val parsed = {name}.from_json(JsonReader(json))
                assert_eq({name}.DEFAULT, parsed)
            }}

        "#, name = self.name});

        push!(s, "sealed class ", &self.name, " {\n");
        for mut f in self.common_props.clone() {
            push!(s, T1, "abstract ");
            f.required = true;
            f.generate(s);
            s.push('\n');
        }

        // s.push_str("\n    abstract fun into_json(): String\n\n");

        for v in &self.variants {
            let ident = format!("{}.{}", self.name, v.name);
            tb.push_str(&formatdoc! {r#"
                run {{
                    Logger.verbose("milf", "{name}")
                    val json = {name}.DEFAULT.into_json()
                    Logger.debug("milf", "json: $json")
                    val parsed = {name}.from_json(JsonReader(json))
                    assert_eq({name}.DEFAULT, parsed)
                }}
            "#, name = ident});
            // tb.push_str(&format!(
            //         r#"    Logger.debug("milf", "{}.{}: " + {}.{}.DEFAULT.into_json())"#,
            //         te.name, v.name,
            //         te.name, v.name
            //     ));
            // tb.push('\n');

            if self.common_props.is_empty() && v.fields.is_empty() {
                push! {s,
                    T1, "data object ", &v.name, " : IntoJson, FromJson<", &ident, ">, ",
                    &self.name, " () {\n",
                    T2, "override fun into_json() =",
                    &format!(r#" """{{"{}": "{}"}}""" "#, self.tag, v.key),
                    "\n\n",
                    T2, "val DEFAULT = ", &ident, "\n\n",
                    T2, "override fun from_json(json_reader: JsonReader): ",
                    &ident, " {\n",
                    T3, "json_reader.begin_obj()\n",
                    T3, "val tag = json_reader.next_name()\n",
                    T3, "if (tag != \"", &self.tag, "\") throw JsonParseException(\"invalid tag: $tag\")\n",
                    T3, "val key = json_reader.next_string()\n",
                    T3, "if (key != \"", &v.key, "\") throw JsonParseException(\"mismatch key: $key\")\n",
                    T3, "json_reader.end_obj()\n",
                    T3, "return ", &ident, "\n", T2, "}\n",
                    T1, "}\n\n"
                };
                continue;
            }

            push!(s, T1, "data class ", &v.name, " (\n");
            for f in &self.common_props {
                push!(s, T2, "override ");
                f.generate(s);
                s.push_str(",\n");
            }

            for f in &v.fields {
                s.push_str(T2);
                f.generate(s);
                s.push_str(",\n");
            }
            push!(s, T1, ") : IntoJson, ", &self.name, "() {\n", T2);
            push!(s, "override fun into_json() = buildString {\n", T3);
            s.push_str(&format!(
                r#"append("""{{"{}": "{}"""")"#,
                self.tag, v.key
            ));
            s.push_str("\n");
            for f in self.common_props.iter() {
                s.push_str(T3);
                f.into_json(s, false);
                s.push('\n');
            }

            for f in v.fields.iter() {
                s.push_str(T3);
                f.into_json(s, false);
                s.push('\n');
            }

            push! {s,
                T3, "append(\"}\")\n", T2, "}\n\n",
                T2, "companion object: FromJson<", &ident, "> {\n",
                T3, "val DEFAULT = ", &ident, "("
            };

            for f in self.common_props.iter() {
                push!(s, &f.name, " = ", &f.ty.default_value(), ",");
            }

            for f in v.fields.iter() {
                push!(s, &f.name, " = ", &f.ty.default_value(), ",");
            }
            s.pop();
            s.push_str(")\n\n");

            push! {s,
                T3, "override fun from_json(json_reader: JsonReader): ",
                &ident, " {\n",
                T4, "Logger.debug(\"milf\", \"", &ident, "\")\n",
                T4, "Logger.debug(\"milf\", json_reader.debug())\n",
                T4, "json_reader.begin_obj()\n"
            };

            for f in self.common_props.iter() {
                push! {s, T4, "var unn_", &f.name, ": ", &f.ty.generate(), "? = null\n"};
            }
            for f in v.fields.iter() {
                push! {s, T4, "var unn_", &f.name, ": ", &f.ty.generate(), "? = null\n"};
            }

            push!(s, "\n", T4, "while (json_reader.has_next()) {\n");
            push!(s, T5, "when (json_reader.next_name()) {\n");
            for f in self.common_props.iter() {
                push! {s, T6, "\"", &f.name ,"\" -> unn_", &f.name, " = ", &f.ty.from_json(), "\n"};
            }
            for f in v.fields.iter() {
                push! {s, T6, "\"", &f.name ,"\" -> unn_", &f.name, " = ", &f.ty.from_json(), "\n"};
            }
            push! {s,
                T6, "\"", &self.tag, "\" -> if (json_reader.next_string() != \"",
                &v.key,"\") throw JsonParseException(\"tag mismatch\")\n",
                T6, "else -> json_reader.skip_value()\n",
                T5, "}\n", T4, "}\n",
                T4, "json_reader.end_obj()\n\n",
                T4, "return ", &ident, "(\n"
            };

            for f in self.common_props.iter() {
                push!(s, T5, &f.name, " = unn_", &f.name);
                if f.required && !f.ty.is_option() {
                    push! {s, "?: throw JsonParseException(\"Missing '", &f.name, "'\")"};
                }
                s.push_str(",\n");
            }
            for f in v.fields.iter() {
                push!(s, T5, &f.name, " = unn_", &f.name);
                if f.required && !f.ty.is_option() {
                    push! {s, "?: throw JsonParseException(\"Missing '", &f.name, "'\")"};
                }
                s.push_str(",\n");
            }
            push!(s, T4, ")\n", T3, "}\n", T2, "}\n", T1, "}\n\n");
        }

        // tb.push_str(&format!(
        //     r#"    Logger.verbose("milf", "{}: " + {}.DEFAULT)"#,
        //     te.name, te.name
        // ));
        // tb.push('\n');

        let dv = &self.variants[0];
        push! {s,
            T1, "companion object: FromJson<", &self.name, "> {\n",
            T2, "val DEFAULT by lazy { ", &self.name, ".", &dv.name, ".DEFAULT }\n\n",
            T2, "override fun from_json(json_reader: JsonReader): ", &self.name, " {\n",
            T3, "Logger.debug(\"milf\", \"", &self.name, "\")\n",
            T3, "Logger.debug(\"milf\", json_reader.debug())\n",
            T3, "val tag = json_reader.peek_tag(\"", &self.tag, "\")\n",
            T3, "when (tag) {\n"
        };

        for v in &self.variants {
            push! {s,
                T4, "\"", &v.key, "\" -> return ",
                &self.name, ".", &v.name, ".from_json(json_reader)\n"
            };
        }
        push!(
            s,
            T4,
            "else -> throw JsonParseException(\"unknown tag $tag\")\n"
        );

        push!(s, T3, "}\n", T2, "}\n", T1, "}\n}\n\n");
    }
}

impl KotlinObject {
    pub fn generate(&self, s: &mut String, tb: &mut String) {
        if !self.is_multipart {
            tb.push_str(&formatdoc! {r#"
                run {{
                    Logger.verbose("milf", "{name}")
                    val json = {name}.DEFAULT.into_json()
                    Logger.verbose("milf", "json: $json")
                    val parsed = {name}.from_json(JsonReader(json))
                    assert_eq({name}.DEFAULT, parsed)
                }}
            "#, name = self.name});
        }

        push!(s, "data class ", &self.name, " (\n");
        for f in self.fields.iter() {
            s.push_str(T1);
            f.generate(s);
            s.push_str(",\n");
        }
        s.push(')');

        if !self.is_multipart {
            push!(s, ": IntoJson");
            s.push_str(" {\n");
            push!(s, T1, "override fun into_json() = buildString {\n");
            push!(s, T2, "append(\"{\")\n");
            for (idx, f) in self.fields.iter().enumerate() {
                s.push_str(T2);
                f.into_json(s, idx == 0);
                s.push('\n');
            }
            push!(s, T2, "append(\"}\")\n");
            push!(s, T1, "}\n\n");

            push!(s, T1, "companion object");
            push!(s, ": FromJson<", &self.name, ">");

            push!(s, " {\n", T2, "val DEFAULT = ", &self.name, "(");
            for (idx, f) in self.fields.iter().enumerate() {
                if idx != 0 {
                    s.push_str(", ");
                }
                push!(s, &f.name, " = ", &f.ty.default_value());
            }
            s.push_str(")\n\n");

            push! {s, T2,
                "override fun from_json(json_reader: JsonReader) : ",
                &self.name, " {\n",
                T3, "Logger.debug(\"milf\", \"", &self.name, "\")\n",
                T3, "Logger.debug(\"milf\", json_reader.debug())\n",
                T3, "json_reader.begin_obj()\n"
            };
            for f in self.fields.iter() {
                push! {s, T3, "var unn_", &f.name, ": ", &f.ty.generate(), "? = null\n"};
            }
            push!(s, "\n");
            push!(s, T3, "while (json_reader.has_next()) {\n");
            push!(s, T4, "when (json_reader.next_name()) {\n");
            for f in self.fields.iter() {
                push! {s, T5, "\"", &f.name ,"\" -> unn_", &f.name, " = ", &f.ty.from_json(), "\n"};
            }
            push! {s, T5, "else -> json_reader.skip_value()\n"};
            push! {s, T4, "}\n", T3, "}\n"};
            push! {s, T3, "json_reader.end_obj()\n"};
            push! {s, T3, "return ", &self.name, "(\n"};

            for f in self.fields.iter() {
                push!(s, T4, &f.name, " = unn_", &f.name);
                if f.required && !f.ty.is_option() {
                    push! {s, "?: throw JsonParseException(\"Missing '", &f.name, "'\")"};
                }
                s.push_str(",\n");
            }

            push!(s, T3, ")\n", T2, "}\n");
            push!(s, T1, "}\n}");
        }
        s.push_str("\n\n");

    }
}

impl KotlinPrim {
    pub fn generate(&self) -> String {
        match self {
            Self::Str => "String".to_string(),
            Self::Int => "Int".to_string(),
            Self::Float => "Double".to_string(),
            Self::Bool => "Boolean".to_string(),
            Self::File => "MultipartBody.Part".to_string(),
            // Self::File => "String".to_string(),
            Self::Ref(r) => format!("gooje.abi.{r}"),
            Self::Option(opt) => format!("{}?", opt.generate()),
            Self::Array(v) => format!("List<{}>", v.generate()),
            Self::Map(m) => format!("Map<String, {}>", m.generate()),
        }
    }

    pub fn default_value(&self) -> String {
        match self {
            Self::Str => "\"\"".to_string(),
            Self::Int => "0".to_string(),
            Self::Float => "0.0".to_string(),
            Self::Bool => "false".to_string(),
            Self::File => unreachable!(),
            Self::Ref(r) => format!("gooje.abi.{r}.DEFAULT"),
            Self::Option(_) => "null".to_string(),
            Self::Array(_) => "listOf()".to_string(),
            Self::Map(_) => "mapOf()".to_string(),
        }
    }

    pub fn from_json(&self) -> String {
        match self {
            Self::Str => "json_reader.next_string()".to_string(),
            Self::Int => "json_reader.next_int()".to_string(),
            Self::Float => "json_reader.next_double()".to_string(),
            Self::Bool => "json_reader.next_bool()".to_string(),
            Self::File => unreachable!(),
            Self::Ref(r) => format!("gooje.abi.{r}.from_json(json_reader)"),
            Self::Option(kp) => {
                format!(
                    "if (json_reader.is_next_null()) {{ json_reader.next_null(); null }} else {{ {} }}",
                    kp.from_json()
                )
            }
            Self::Array(v) => {
                formatdoc!(
                    r#"run {{
                    json_reader.begin_array()
                    val temp = mutableListOf<{}>()
                    while (json_reader.has_next()) {{
                        temp.add({})
                    }}
                    json_reader.end_array()
                    temp
                }}"#,
                    v.generate(),
                    v.from_json()
                )
            }
            Self::Map(v) => {
                formatdoc!(
                    r#"run {{
                    json_reader.begin_obj()
                    val temp = mutableMapOf<String, {}>()
                    while (json_reader.has_next()) {{
                        val key = json_reader.next_name()
                        temp.put(key, {} ?: throw JsonParseException("item is null"))
                    }}
                    json_reader.end_obj()
                    temp
                }}"#,
                    v.generate(),
                    v.from_json()
                )
            }
        }
    }

    pub fn into_json(&self, val: &str, s: &mut String) {
        match self {
            KotlinPrim::Str => {
                s.push_str(&format!("append(into_json({val}))"));
                // s.push_str(&format!(r#"append(""""${val}",""");"#));
            }
            KotlinPrim::Int | KotlinPrim::Float => {
                s.push_str(&format!("append(into_json({val}))"));
                // s.push_str(&format!(r#"append({val});"#));
                // s.push_str(r#"append(",");"#);
            }
            KotlinPrim::Bool => {
                s.push_str(&format!("append(into_json({val}))"));
                // s.push_str(&format!(r#"append({val});"#));
                // s.push_str(r#"append(",");"#);
            }
            KotlinPrim::Ref(_) => {
                s.push_str(&format!(r#"append(into_json({val}))"#));
                // s.push_str(r#"append(",");"#);
            }
            KotlinPrim::Option(_) => {
                s.push_str(&format!(r#"append(into_json({val}))"#));
                // s.push_str(&format!(r#"if ({val} == null) append("null,") else {{ "#));
                // opt.into_json(val, s);
                // s.push_str(" };");
            }
            KotlinPrim::Array(_) => {
                s.push_str(&format!(r#"append(into_json({val}))"#));
                // s.push_str(r#"append("["); "#);
                // s.push_str(&format!(r#"for (item in {val}) {{ append(item.into_json());append(","); }}; deleteAt(lastIndex); "#));
                // s.push_str(r#"append("]");"#);
            }
            KotlinPrim::Map(_) => {
                s.push_str(&format!(r#"append(into_json({val}))"#));
                // s.push_str(r#"append("{");"#);
                // s.push_str(&format!(r#" for ((key, item) in {val}) {{ append(""" "$key": """);append(item.into_json());append(",") }}; deleteAt(lastIndex); "#));
                // s.push_str(r#"append("}");"#);
            }
            KotlinPrim::File => unreachable!(),
        }
    }
}

impl ObjectField {
    pub fn generate(&self, s: &mut String) {
        s.push_str("val ");
        s.push_str(&self.name);
        s.push_str(": ");
        s.push_str(&self.ty.generate());
        if !self.required {
            if !self.ty.is_option() {
                s.push_str("?");
            }
            s.push_str(" = null");
            return;
        }
        // if let Some(dv) = &self.ty.default_value() {
        //     s.push_str(" = ");
        //     s.push_str(dv);
        // }
    }

    pub fn into_json(&self, s: &mut String, is_first: bool) {
        let comma = if is_first { "" } else { "," };
        s.push_str(&format!(r#"append("""{comma}"{}":""");"#, self.name));

        // if !self.required && !self.ty.is_option() {
        //     s.push_str(&format!(
        //         r#"if ({} == null) append("null,") else {{"#,
        //         // r#"${{if ({} == null) "null" else "{}"}}"#,
        //         self.name,
        //     ));
        //     self.ty.into_json(&self.name, s);
        //     s.push_str("};");
        //     return;
        // }

        self.ty.into_json(&self.name, s);
    }
}
