use std::io::Write;

use indoc::formatdoc;

use super::*;

impl KotlinApi {
    pub fn generate(&self) -> std::io::Result<()> {
        let mut s = String::with_capacity(2 * 1024 * 1024);
        let mut tb = String::with_capacity(2 * 1024 * 1024);
        let mut kotlin = std::fs::OpenOptions::new()
            .write(true)
            .create(true)
            .truncate(true)
            .open("argon-data/gen.kt")?;

        kotlin.write_all(
            formatdoc! {r#"
                package app.gooje.test.api

                // import okhttp3.MultipartBody


                // import kotlinx.serialization.Serializable
                // import kotlinx.serialization.SerialName
                // DO NOT EDIT THIS FILE.
                // THIS IS A GENERATED FILE AND ANY EDIT WILL BE REPLACED
                // Home: github.com/00-team/argon
                // import * as ud from './user_defined';
                // const val API_VERSION = "{}";


                interface IntoJson {{
                    fun into_json(): String
                }}
                
                private fun json_escape(str: String): String = 
                    str.replace("\\", "\\\\").replace("\"", "\\\"")
                
                // object StringEncoder : IntoJson<String> {{
                //     override fun String.into_json(): String = "\"${{json_escape(this)}}\""
                // }}
                // 
                // object IntEncoder : IntoJson<Int> {{
                //     override fun Int.into_json(): String = toString()
                // }}
                // 
                // fun <T> List<T>.into_json(): String {{
                //     return buildString {{
                //         append("[")
                //         forEachIndexed {{ index, item ->
                //             if (index > 0) append(",")
                //             append(item.into_json())
                //         }}
                //         append("]")
                //     }}
                // }}


                // The one and only function
                fun into_json(value: Any?): String = when (value) {{
                    null -> "null"
                    is String -> "\"${{json_escape(value)}}\""
                    is Number, is Boolean -> value.toString()
                    is List<*> -> value.joinToString(prefix = "[", postfix = "]") {{ into_json(it) }}
                    is Map<*, *> -> value.entries.joinToString(prefix = "{{", postfix = "}}") {{ (k, v) ->
                        "\"$k\":${{into_json(v)}}"
                    }}
                    is IntoJson -> value.into_json()
                    else -> error("Don't know how to convert ${{value::class.simpleName}} to JSON")
                }}
                
                // Optional: extension method for dot syntax
                // fun Any?.into_json() = into_json(this)

                interface FromJson<T> {{
                    fun from_json(json: String): T?
                }}


            "#, self.api_version}
            .as_bytes(),
        )?;

        tb.push_str("fun test() {\n\n");

        for (name, kp) in &self.typealias {
            s += &formatdoc! {r#"
                @JvmInline
                value class {name}(private val value: {}): IntoJson {{
                    override fun into_json() = into_json(value);

                    companion object {{
                        val DEFAULT = {name}({})
                    }}
                }}
            "#, kp.generate(), kp.default_value()
            };

            tb.push_str(&format!(
                "    Logger.debug(\"milf\", {name}.DEFAULT.into_json())\n"
            ));
        }

        for se in &self.str_enums {
            s.push_str("enum class ");
            s.push_str(&se.name);
            s.push_str(" : IntoJson {\n   ");
            for v in &se.variants {
                s.push(' ');
                s.push_str(&v.to_uppercase());
                s.push_str(",");
            }
            s.pop();
            s.push_str(
                ";\n\n    override fun into_json(): String = when(this) {\n",
            );

            for v in &se.variants {
                s.push_str("        ");
                s.push_str(&v.to_uppercase());
                s.push_str(" -> ");
                s.push_str(r#""\""#);
                s.push_str(v);
                s.push_str(r#"\"""#);
                s.push('\n');
            }

            s.push_str("    }\n\n");

            s.push_str("    companion object {\n        val DEFAULT = ");
            s.push_str(&se.variants[0].to_uppercase());

            s.push_str("\n    }\n}\n");

            tb.push_str(&format!(
                "    Logger.debug(\"milf\", {}.DEFAULT.into_json())\n",
                se.name
            ));
        }

        for kob in &self.objects {
            s.push_str("data class ");
            s.push_str(&kob.name);
            s.push_str(" (\n");
            let mut into_json = String::with_capacity(512);
            let mut default = String::with_capacity(512);
            for (idx, f) in kob.fields.iter().enumerate() {
                s.push_str("    ");
                f.generate(&mut s);
                s.push_str(",\n");

                default.push_str(&f.name);
                default.push_str(" = ");
                default.push_str(&f.ty.default_value());
                default.push_str(",");

                if kob.is_multipart {
                    continue;
                }
                if !into_json.is_empty() {
                    into_json.push_str("        ");
                }
                f.into_json(&mut into_json, idx == 0);
                into_json.push('\n');
                // into_json.push(',');
            }
            // into_json.push_str("        ");
            // into_json.push_str("deleteAt(lastIndex);");
            default.pop();
            // into_json.pop();

            s += &formatdoc! {r#"): IntoJson {{
                override fun into_json() = buildString {{
                    append("{{");
                    {into_json}
                    append("}}");
                }}
            
                companion object {{
                    val DEFAULT = {}({default})
                //     fun from_json(raw: String) : {} {{
                //         
                //     }}
                }}
            }}"#, kob.name, kob.name};
            s.push_str("\n\n");

            tb.push_str(&format!(
                "    Logger.debug(\"milf\", {}.DEFAULT.into_json())\n",
                kob.name
            ));
        }

        for te in &self.tagged_enums {
            // te.tag
            // te.variants
            // te.common_props

            s.push_str("sealed class ");
            s.push_str(&te.name);
            s.push_str(" {\n");
            for mut f in te.common_props.clone() {
                s.push_str("    abstract ");
                f.required = true;
                f.generate(&mut s);
                s.push('\n');
            }

            // s.push_str("\n    abstract fun into_json(): String\n\n");

            for v in &te.variants {
                if te.common_props.is_empty() && v.fields.is_empty() {
                    s.push_str("    data object ");
                    s.push_str(&v.name);
                    s.push_str(" : IntoJson, ");
                    s.push_str(&te.name);
                    s.push_str("() {\n        ");
                    s.push_str(&format!(
                        r#"override fun into_json() = """{{"{}": "{}"}}""""#,
                        te.tag, v.key
                    ));
                    s.push_str("\n    }\n\n");
                    continue;
                }
                s.push_str("    data class ");
                // s.push_str(&snake_to_pascal(&v.name));
                s.push_str(&v.name);
                s.push_str(" (\n");
                for f in &te.common_props {
                    s.push_str("        override ");
                    f.generate(&mut s);
                    s.push_str(",\n");
                }

                for f in &v.fields {
                    s.push_str("        ");
                    f.generate(&mut s);
                    s.push_str(",\n");
                }
                s.push_str("    ) : IntoJson, ");
                s.push_str(&te.name);
                s.push_str("() {\n        ");
                s.push_str("override fun into_json() = buildString {\n");
                s.push_str(&format!(
                    r#"append("""{{"{}": "{}",""")"#,
                    te.tag, v.key
                ));
                s.push_str("\n");
                for f in te.common_props.iter() {
                    f.into_json(&mut s, false);
                    s.push('\n');
                }

                for f in v.fields.iter() {
                    f.into_json(&mut s, false);
                    s.push('\n');
                }

                s.push_str(r#"append("}")"#);
                s.push_str("\n        }\n    }\n\n");
                s.push_str("\n        }\n");

                s.push_str("        companion object {");
                s.push_str("val DEFAULT = ");

                s.push_str(&v.name);

                if !te.common_props.is_empty() || !v.fields.is_empty() {
                    s.push_str("(");
                    for f in te.common_props.iter() {
                        s.push_str(&f.name);
                        s.push_str(" = ");
                        s.push_str(&f.ty.default_value());
                        s.push_str(",");
                    }

                    for f in v.fields.iter() {
                        s.push_str(&f.name);
                        s.push_str(" = ");
                        s.push_str(&f.ty.default_value());
                        s.push_str(",");
                    }
                    s.pop();
                    s.push_str(")");
                }

                s.push_str("\n        }\n    }\n\n");
            }

            s.push_str("    companion object {\n        val DEFAULT = ");
            // s.push_str(&te.name);
            // s.push_str(".");
            let dv = &te.variants[0];
            s.push_str(&dv.name);
            s.push_str(".DEFAULT");

            s.push_str("\n    }\n");

            s.push_str("}\n");
        }
        s.push_str("\n\n");
        tb.push_str("}\n");

        kotlin.write_all(s.as_bytes())?;
        kotlin.write_all(tb.as_bytes())?;

        Ok(())
    }
}

impl KotlinPrim {
    pub fn generate(&self) -> String {
        match self {
            Self::Str => "String".to_string(),
            Self::Int => "Int".to_string(),
            Self::Float => "Double".to_string(),
            Self::Bool => "Boolean".to_string(),
            // Self::File => "MultipartBody.Part".to_string(),
            Self::File => "String".to_string(),
            Self::Ref(r) => r.clone(),
            Self::Option(opt) => format!("{}?", opt.generate()),
            Self::Array(v) => format!("List<{}>", v.generate()),
            Self::Map(m) => format!("Map<String, {}>", m.generate()),
        }
    }

    pub fn default_value(&self) -> String {
        match self {
            Self::Str => "\"\"".to_string(),
            Self::Int => "0".to_string(),
            Self::Float => "0.0".to_string(),
            Self::Bool => "false".to_string(),
            Self::File => "\"\"".to_string(),
            Self::Ref(r) => format!("{r}.DEFAULT"),
            Self::Option(_) => "null".to_string(),
            Self::Array(_) => "listOf()".to_string(),
            Self::Map(_) => "mapOf()".to_string(),
        }
    }

    pub fn into_json(&self, val: &str, s: &mut String) {
        match self {
            KotlinPrim::Str => {
                s.push_str(&format!("append(into_json({val}))"));
                // s.push_str(&format!(r#"append(""""${val}",""");"#));
            }
            KotlinPrim::Int | KotlinPrim::Float => {
                s.push_str(&format!("append(into_json({val}))"));
                // s.push_str(&format!(r#"append({val});"#));
                // s.push_str(r#"append(",");"#);
            }
            KotlinPrim::Bool => {
                s.push_str(&format!("append(into_json({val}))"));
                // s.push_str(&format!(r#"append({val});"#));
                // s.push_str(r#"append(",");"#);
            }
            KotlinPrim::Ref(_) => {
                s.push_str(&format!(r#"append(into_json({val}))"#));
                // s.push_str(r#"append(",");"#);
            }
            KotlinPrim::Option(_) => {
                s.push_str(&format!(r#"append(into_json({val}))"#));
                // s.push_str(&format!(r#"if ({val} == null) append("null,") else {{ "#));
                // opt.into_json(val, s);
                // s.push_str(" };");
            }
            KotlinPrim::Array(_) => {
                s.push_str(&format!(r#"append(into_json({val}))"#));
                // s.push_str(r#"append("["); "#);
                // s.push_str(&format!(r#"for (item in {val}) {{ append(item.into_json());append(","); }}; deleteAt(lastIndex); "#));
                // s.push_str(r#"append("]");"#);
            }
            KotlinPrim::Map(_) => {
                s.push_str(&format!(r#"append(into_json({val}))"#));
                // s.push_str(r#"append("{");"#);
                // s.push_str(&format!(r#" for ((key, item) in {val}) {{ append(""" "$key": """);append(item.into_json());append(",") }}; deleteAt(lastIndex); "#));
                // s.push_str(r#"append("}");"#);
            }
            KotlinPrim::File => unreachable!(),
        }
    }
}

impl ObjectField {
    pub fn generate(&self, s: &mut String) {
        s.push_str("val ");
        s.push_str(&self.name);
        s.push_str(": ");
        s.push_str(&self.ty.generate());
        if !self.required {
            if !self.ty.is_option() {
                s.push_str("?");
            }
            s.push_str(" = null");
            return;
        }
        // if let Some(dv) = &self.ty.default_value() {
        //     s.push_str(" = ");
        //     s.push_str(dv);
        // }
    }

    pub fn into_json(&self, s: &mut String, is_first: bool) {
        let comma = if is_first { "" } else { "," };
        s.push_str(&format!(r#"append("""{comma}"{}":""");"#, self.name));

        // if !self.required && !self.ty.is_option() {
        //     s.push_str(&format!(
        //         r#"if ({} == null) append("null,") else {{"#,
        //         // r#"${{if ({} == null) "null" else "{}"}}"#,
        //         self.name,
        //     ));
        //     self.ty.into_json(&self.name, s);
        //     s.push_str("};");
        //     return;
        // }

        self.ty.into_json(&self.name, s);
    }
}
